import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const Home: NextPage = (props) => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-3xl font-semibold">My Shopping List</h2>
          <button className=" rounded bg-purple-600 p-2 font-semibold text-white transition hover:bg-purple-500">
            + Add Shopping Item
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
